---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# melsvmp

<!-- badges: start -->
<!-- badges: end -->

The goal of melsvmp is to ...

## Installation

You can install the development version of melsvmp like so:

```{r}

```


## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(melsvmp)

riesby <- read.table("RIESBY.DAT.txt", na.strings = ".", 
                     col.names = c("id", "hamd", "intcpt", "week", "endog", "endweek"))

riesby_ncvmp <- mels_ncvmp(y = "hamd", 
                           beta_formula = ~ week + endog + endweek, 
                           alpha_formula = ~ endog, 
                           tau_formula = ~ week + endog, 
                           id = "id",
                           data = riesby)
summary(riesby_ncvmp)
```

```{r}
riesby_ncvmp_boot <- bootstrap_mels_ncvmp(riesby_ncvmp, B = 1000, cores = 10)
summary(riesby_ncvmp_boot)
```

